# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickSandA', '0003_auto_20160820_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='lactose_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='nut_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
